#springboot_config
server:
  port: 8080

# jdbc_config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/base2?characterEncoding=utf8
    username: root
    password: admin
  resources:
    static-locations: classpath:/static/
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss

# jpa 
#spring.jpa.show-sql: true
#spring.jpa.properties.jadira.usertype.autoRegisterUserTypes: true
#spring.jpa.hibernate.ddl-auto: none

# mybatis
mybatis:
  type-aliases-package: net.sppan.base.entity.*
  mapper-locations: 
    classpath: net/sppan/base/mapper/*.xml
#通用mapper
mapper: 
  mappers:
    - net.sppan.base.common.Mappers
  not-empty: false
  identity: MYSQL
